version: "3"
services:

  redis:
    image: redis:windowsservercore
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: ${DELAY:?DelayErr10s}
      restart_policy:
        condition: ${CONDITION}
  vote:
    image: dockersamples/examplevotingapp_vote:dotnet-nanoserver-sac2016
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
networks:
  frontend:
  backend:

volumes:
  db-data: