version: "3"
services:
  redis:
    image: redis:windowsservercore
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: ${DELAY:?DelayErr10s}
      restart_policy:
        condition: ${CONDITION}
    environment:
      REDIS_HOST: ${RD_HOST:-myhost}
      REDIS_NAME: ${RD_NAME-myname}
      REDIS_USER: ${RD_USER?UserErr}
      REDIS_PASSWORD: examplePW
networks:
  frontend: