version: "3"
services:
  message-queue:
    image: nats:nanoserver
    deploy:
      endpoint_mode: ${MODE:-dnsrr}
    container_name: ${CON_NAME-mymessage}
    environment:
      JAVA_OPTS: -Duser.timezone=Asia/Shanghai
      MessageQueue_HOST: ${MQ_HOST}
      MessageQueue_NAME: ${MQ_NAME:?NameErr}
      MessageQueue_USER: ${MQ_USER?UserErr}
      MessageQueue_PASSWORD: examplePW
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: ${DELAY:?DelayErr10s}
      restart_policy:
        condition: ${CONDITION}
networks:
  frontend: