version: '3'

services:

  redis:
    image: redis
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  example:
    image: crystalcui8/publictest:lin

volumes:
  mysql-data: