version: "3.2"

services:
  message-queue:
    image: nats:nanoserver
    deploy:
      endpoint_mode: ${MODE:-dnsrr}
    container_name: ${CON_NAME-mymessage}
    environment:
      JAVA_OPTS: -Duser.timezone=Asia/Shanghai
      MessageQueue_HOST: ${MQ_HOST}
      MessageQueue_NAME: ${MQ_NAME:?NameErr}
      MessageQueue_USER: ${MQ_USER?UserErr}
      MessageQueue_PASSWORD: examplePW
    networks:
      - backend
networks:
  backend:
