version: '3'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-mysql}
      WORDPRESS_DB_NAME: ${DB_NAME-wordpress}
      WORDPRESS_DB_USER: example
      WORDPRESS_DB_PASSWORD: examplePW
      NEWVAR: ${NEWVAR:?NewvarErr}
    volumes:
      - ./wordpress-data:/var/www/html

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: examplerootPW
      MYSQL_DATABASE: wordpress
      MYSQL_USER: example
      MYSQL_PASSWORD: examplePW
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  default:
    name: ${NET_NAME?NetError}
    driver: bridge
